Repository Fuenfgeld/DMA2023TeamA, pull requests merged in 2023-02, with the labels that each got.

#46 #44 Datentyp für SNOMED CT Codes vereinheitlichen
  Code/Setup_and_fill_Database.ipynb
Labels: refinement

#49 #11 Initiales README-File erstellt
  README.md
Labels: documentation

#48 Update ETL Datenmodell
  Code/ETL_Process.ipynb
  Code/etl_sql_entwurf.sql
  Dokumentation/Sternschema_DWH_Detail_v1.png
  Dokumentation/Sternschema_DWH_Overview_v1.png
  Dokumentation/Sternschema_DWH_v2.png
Labels: refinement

#55 #54 Primärschlüssel in DWH erweitern
  Code/ETL_Process.ipynb
  Code/etl_sql_entwurf.sql
  Dokumentation/Sternschema_DWH_v3.png
Labels: bug, refinement

#61 Indexspalten in Datenbanken definieren
  Code/ETL_Process.ipynb
  Code/Setup_and_fill_Database.ipynb
Labels: refinement

#82 Verifizierung der verarbeiteten Daten mit Checksums
  Code/ETL_Process.ipynb
  Code/Setup_and_fill_Database.ipynb
Labels: enhancement

#79 Durchführung der Datenanalyse
  Code/Data_Analysis.ipynb
  Daten/Analyse/analysis_processed_data.csv
  Daten/Analyse/analysis_raw_data.csv
  Daten/Analyse/dwh_data_costs.csv
  Daten/Analyse/dwh_data_diagnoses.csv
  Ergebnisse/Plots_EDA/01_patients_by_diagnosis.png
  Ergebnisse/Plots_EDA/02_gender_distribution.png
  Ergebnisse/Plots_EDA/03_gender_by_diagnosis.png
  Ergebnisse/Plots_EDA/04_ethnicity.png
  Ergebnisse/Plots_EDA/05_ethnicity_by_diagnosis.png
  Ergebnisse/Plots_EDA/06_medication_cost.png
  Ergebnisse/Plots_EDA/07_healthcare_cost_by_diagnosis.png
  Ergebnisse/Plots_EDA/08_healthcare_cost_pro_by_diagnosis.png
  Ergebnisse/Plots_EDA/09_healthcare_encounters_by_diagnosis.png
  Ergebnisse/Plots_MachineLearning/01_decision_tree_cm.png
  Ergebnisse/Plots_MachineLearning/02_logistic_regression_analysis_cm.png
Labels: analysis
